### ISSUE TITLE
Misspelling of optional rpms channel

### ISSUE THREAD

**Issue by kjw3** [oasis-roles/meta_skeleton#26]
in [molecule/shared/prepare.yml](https://github.com/oasis-roles/meta_skeleton/blob/master/molecule/shared/prepare.yml)

rhsl-7-server-optional-rpms

Should be

rhel-7-server-optional-rpms

**Comment by greg-hellings** [comment]
I was just staring at this yesterday thinking, "This has GOT to be a typo". But it's never resulted in a bad behavior that I've noticed, so I hadn't done anything about it. We'll get this one sorted out ASAP

**Comment by greg-hellings** [comment]
Wow, I could have sworn this had gotten fixed back when it was reported. Thanks for that, @robled.
