### ISSUE TITLE
Skeleton Templates

### ISSUE THREAD

**Issue by samdoran** [oasis-roles/meta_skeleton#32]
I maintain two Ansible role skeletons for use with Cookiecutter and/or Molecule. They come with a Molecule configuration that is pretty painless to start using as well as a Travis CI configuration. I would be interested in making those official skeletons in this project, or working to incorporate some of the structure of those skeletons into this project.

https://github.com/samdoran/cookiecutter-ansible-role
https://github.com/samdoran/cookiecutter-ansible-role-multi

**Comment by greg-hellings** [comment]
We'd be happy to see pull requests and new features added to this. One thing I would note is that we are not setting up individual roles to be tested in Travis CI anymore. This is for 2 reasons

0 - we have moved our tests to Github Actions, which have a much more generous free tier and have the added advantage of being included in the page
1 - This skeleton is now used to target a role inside of a collection, and so we don't actually run CI at the role level but at the collection level. This is now a companion to the [ansible collection template](https://github.com/oasis-roles/meta_ansible_collection_template), and is intended to create a role inside of that. The collection template contains all our base CI/CD release pipeline.

If you'd like to make some suggestions to improve this role, feel free to open a PR and we can discuss it.
